# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buscador', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SearchUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('searchresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='searchkeyws.SearchResult')),
            ],
        ),
        migrations.CreateModel(
            name='WSRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField()),
                ('nombre_directorio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WSResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='searchresult',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscadores', to='searchkeyws.WSResponse'),
        ),
        migrations.AddField(
            model_name='searchkey',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='searchkeyws.WSRequest'),
        ),
    ]
