# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchkeyws', '0002_auto_20160130_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredurl',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
