# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchkeyws', '0004_auto_20160521_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wsfilteredurlsrequest',
            old_name='id_request',
            new_name='request',
        ),
    ]
