# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchkeyws', '0005_auto_20160521_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSRequestState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1000)),
                ('stop', models.BooleanField()),
                ('request', models.ForeignKey(db_column=b'search_keys', on_delete=django.db.models.deletion.CASCADE, to='searchkeyws.WSRequest')),
            ],
            options={
                'db_table': 'wsrequest_state',
            },
        ),
    ]
