# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-05-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchkeyws', '0006_wsrequeststate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsrequest',
            name='nombre_directorio',
            field=models.CharField(max_length=255),
        ),
    ]
