class TestLinksClass:
    def __init__(self):
        pass
    def getTestLinks(self,urls):#key search: technology to produce tea
        if urls==1:
            return [["https://docs.python.org/2/library/math.html#"]]
            #return [['http://www.agriculture.go.tz/publications/NATIONAL%20AGRICULTURAL%20POLICY%20-2013.doc'],["http://www.sciencedirect.com/science/article/pii/S1226845314000621"]]
        elif urls==2:
            #return [["http://www.clips.ua.ac.be/pages/pattern"],["http://www.teaboard.gov.in/"]]
            #return [[u'https://croplife.org/'],["http://www.clips.ua.ac.be/pages/pattern-vector"]]
            return [["https://docs.python.org/2/library/math.html#"],["http://www.teaboard.gov.in/"]]
        elif urls==5:
            lista=[
                   ["http://www.teauction.com/home/techtrend.asp"],
                   ["http://www.teaboard.gov.in/"],
                   ['http://www.upasitearesearch.org/tea-technology/'],
                   ['https://www.researchgate.net/publication/261071584_A_novel_technology_for_production_of_instant_tea_powder_from_the_existing_black_tea_manufacturing_process'],
                   ['http://comida.uncomo.com/articulo/como-cocer-bien-los-garbanzos-191.html']
                  ]
            return lista
        elif urls==7:
            lista=[
                    [u'http://mda.maryland.gov/foodfeedquality/Pages/good_ag_practices.aspx'],
                    [u'http://www.idhsustainabletrade.com/site/getfile.php?id=272'],
                    [u'http://www.fertilizer.org/en/doc_library/Knowledge%20Resources/IFAposition_post2015SDG_FINAL_7May.pdf'],
                    [u'http://www.lift-fund.org/inclusive-market-development-and-private-sector'],
                    [u'http://dailyranger.com/story.php?story_id=22976'],
                    [u'http://www.agriculture.go.tz/publications/NATIONAL%20AGRICULTURAL%20POLICY%20-2013.doc'],
                    [u'https://croplife.org/'],
                   ]             
            return lista
        elif urls == 165:
            lista=[
                    [u'http://mda.maryland.gov/foodfeedquality/Pages/good_ag_practices.aspx'],
                    [u'http://www.idhsustainabletrade.com/site/getfile.php?id=272'],
                    [u'http://www.fertilizer.org/en/doc_library/Knowledge%20Resources/IFAposition_post2015SDG_FINAL_7May.pdf'],
                    [u'http://www.lift-fund.org/inclusive-market-development-and-private-sector'],
                    [u'http://dailyranger.com/story.php?story_id=22976'],
                    [u'http://www.agriculture.go.tz/publications/NATIONAL%20AGRICULTURAL%20POLICY%20-2013.doc'],
                    [u'https://croplife.org/'],
                    [u'http://searca.org/index.php/news/1116-good-agricultural-practices-gap-how-does-the-philippines-fare'],
                    [u'http://cipotato.org/seed-potato-for-africa/'],
                    [u'http://www.kyagr.com/marketing/GAP.html'],
                    [u'https://malariajournal.biomedcentral.com/articles/10.1186/1475-2875-9-91'],
                    [u'http://www.worldagroforestry.org/sites/default/files/Knowledge%20sharing%20and%20communication%20strategy.pdf'],
                    [u'http://www.fao.org/prods/gap/Docs/PDF/5-GAPworkingConceptPaperEXTERNAL.pdf'],
                    [u'https://www.unilever.com/sustainable-living/transformational-change/mainstreaming-sustainable-agriculture/'],
                    [u'http://siteresources.worldbank.org/INTARD/825826-1111063678817/20431788/Decentralization.pdf'],
                    [u'http://ati.da.gov.ph/rtc3/category/ati-rtc3-terms/GAP%20Certified'],
                    [u'http://www.ccsenet.org/journal/index.php/ass/article/download/24356/15411'],
                    [u'http://www.eufic.org/article/en/page/TARCHIVE/expid/tips-good-hygiene-practices/'],
                    [u'http://www.educationscotland.gov.uk/knowledgeoflanguage/english/commonconfusions/practice/'],
                    [u'http://agr.wa.gov/inspection/gapghp/'],
                    [u'http://onfarmfoodsafety.org/wp-content/uploads/ucdavis-food-safety-audit.pdf'],
                    [u'http://www.ru.nl/publish/pages/721725/cidin_policy_brief-290114.pdf'],
                    [u'http://jifsan.umd.edu/docs/gaps/en/GAPs_Manual_(Compiled).pdf'],
                    [u'http://www.sciencedirect.com/science/article/pii/S1226845314000621'],
                    [u'http://www.propcommaikarfi.org/our-markets/seeds'],
                    [u'http://academics.aces.illinois.edu/career-services/linking-careers/fshn-careers'],
                    [u'http://www.nature.com/nature/journal/v418/n6898/full/nature01014.html'],
                    [u'http://aims.fao.org/fr/areas-of-interests/good-practice'],
                    [u'http://smallb.sidbi.in/sites/default/files/knowledge_base/best_practices/ManualonGoodAgriculturalMarketingPracticesforCotton.pdf'],
                    [u'http://ageconsearch.umn.edu/bitstream/31541/1/22020159.pdf'],
                    [u'http://www.ifc.org/wps/wcm/connect/topics_ext_content/ifc_external_corporate_site/ifc+sustainability/learning+and+adapting/knowledge+products/project+examples/improving_agricultural_practices_coffee_farmers_central_america'],
                    [u'http://searca.org/events/seminar-series/30-events/knowledge-events/seminar-series/922-better-future-for-vietnams-lychee-industry-with-good-agricultural-practice-vietgap'],
                    [u'https://www.researchgate.net/publication/283298351_Impact_of_Good_Agricultural_Practices_GAP_on_Small_Farm_Development_Knowledge_and_Adoption_levels_of_Farm_Women_of_Rainfed_Areas'],
                    [u'http://whqlibdoc.who.int/publications/2003/9241546271.pdf'],
                    [u'https://www.osha.gov/dte/sharwood/best-practices.html'],
                    [u'http://www.sciencedirect.com/science/article/pii/S0956713515002819'],
                    [u'https://www.ces.ncsu.edu/event/705663457/fresh-produce-good-agricultural-practices-workshop-series/'],
                    [u'https://www.unisdr.org/files/3646_IndigenousKnowledgeDRR.pdf'],
                    [u'http://www.heinz.com/sustainability/supplychain/global-ag-program.aspx'],
                    [u'http://www.nacacnet.org/about/Governance/Policies/Documents/SPGP_9_2013.pdf'],
                    [u'http://www.ishs.org/scripta-horticulturae/good-agricultural-practices-african-indigenous-vegetables'],
                    [u'http://efreshglobal.com/eFresh/Content/Free.aspx?u=kgh'],
                    [u'https://www.quora.com/Why-is-soil-conservation-an-essential-agricultural-practice'],
                    [u'http://www.g-fras.org/en/knowledge/global-good-practice-notes.html?download=357:ggp-note-18-using-radio-in-agricultural-extension'],
                    [u'http://dlc.dlib.indiana.edu/dlc/bitstream/handle/10535/2455/PUTTING_LOCAL_KNOWLEDGE_TO_GOOD_USE.pdf?sequence=1'],
                    [u'http://ap.fftc.agnet.org/ap_db.php?id=558'],
                    [u'http://www.origin-gi.com/images/stories/PDFs/Asia_Invest_Alliance_EN.pdf'],
                    [u'http://www.taproduce.com/trade/agricultural-practices.php'],
                    [u'http://12.000.scripts.mit.edu/mission2014/solutions/farmer-education-agricultural-extension'],
                    [u'https://ncfreshproducesafety.ces.ncsu.edu/spotlight/fresh-produce-good-agricultural-practices-workshop-series/'],
                    [u'http://www.preventionweb.net/files/10479_10479CommunityBasedDRRGoodPracticeR.pdf'],
                    [u'http://www.worldbank.org/afr/ik/ikpaper_0102.pdf'],
                    [u'http://www.fao.org/wssd/sard/documents/faogapen.doc'],
                    [u'http://ec.europa.eu/agriculture/fore/publi/forest_brochure_en.pdf'],
                    [u'https://www.bae.ncsu.edu/academic/ag-work.php'],
                    [u'http://www.seea.org.in/vol10-1-2010/17.pdf'],
                    [u'http://willamette.edu/cla/additional-academic-opportunities/debate/pdf/youth_forum/mtt%20research/technological%20advances/Dea_Local%20Knowledge_Farming.pdf'],
                    [u'http://www.ciatnews.cgiar.org/2015/07/01/apc-colombia-and-ciat-partners-in-fostering-good-agricultural-practices/'],
                    [u'https://www.carolinafarmstewards.org/expert-tip-the-good-agricultural-practices-gaps-audit-process/'],
                    [u'http://www.new-ag.info/en/pov/views.php?a=1031'],
                    [u'http://www.kakaoforum.de/fileadmin/user_uploads/Summary_of_the_CCE_follow-up_study__19_02_2014__2_.pdf'],
                    [u'http://www.unesco.org/most/bpikpub.htm'],
                    [u'http://scholar.lib.vt.edu/ejournals/JITE/v32n2/hansen.html'],
                    [u'http://www.newforesight.com/agricultural-projects/cocoaaction-strategy-fueled-by-industry-leaders-desire-to-accelerate-sustainability-in-the-cocoa-sector/'],
                    [u'https://www.pepsico.com/docs/album/sustainability-reporting/water-agriculture-reports/pepsico_agri_0531_final.pdf?sfvrsn=2'],
                    [u'http://www.wikihow.com/Practice-Sustainable-Agriculture'],
                    [u'https://www.povertyactionlab.org/evaluation/contract-farming-technology-adoption-and-agricultural-productivity-evidence-small-scale'],
                    [u'http://www.literacybridge.org/2014/12/15/ghanas-best-farmers-are-talking-book-users/'],
                    [u'http://www.scidev.net/global/data/opinion/finding-the-real-impact-of-agricultural-innovation-support.html'],
                    [u'http://www.southernsare.org/Educational-Resources/SARE-Project-Products/Books-Manuals-and-Training-Guides/Good-Agricultural-Practices'],
                    [u'https://www.akf.org.uk/examples-of-our-work/agriculture/'],
                    [u'http://www.fao.org/docrep/013/i1645e/i1645e00.pdf'],
                    [u'https://www.cals.ncsu.edu/CollegeRelations/AGRICU.htm'],
                    [u'http://apps.who.int/medicinedocs/en/d/Js4928e/9.html'],
                    [u'http://aims.fao.org/zh-hans/areas-of-interests/good-practice'],
                    [u'http://www.docin.com/p-1292507127.html'],
                    [u'https://labor.idaho.gov/dhr/ats/statejobs/Specs.aspx?Class_No=00412'],
                    [u'http://www.calpistachioresearch.org/GAP_Self_Assessment_2013.pdf'],
                    [u'http://www.nature.com/scitable/knowledge/soil-agriculture-and-agricultural-biotechnology-84826767'],
                    [u'http://www.dlist.org/book/export/html/1024'],
                    [u'http://www.uky.edu/~deberti/test/sust.htm'],
                    [u'http://smallb.in/sites/default/files/knowledge_base/best_practices/ManualonGoodAgriculturalMarketingPracticesforCotton.pdf'],
                    [u'http://www.knowledgebank.irri.org/'],
                    [u'http://bookwashangry.top/read-document/innovative-soil-plant-systems-for-sustainable-agricultural-practices.pdf'],
                    [u'http://ec.europa.eu/environment/water/water-nitrates/index_en.html'],
                    [u'https://www.utz.org/wp-content/uploads/2015/12/Cote-d-ivoire-report-highlights-UTZ.pdf'],
                    [u'http://www.wudpeckerresearchjournals.org/WJAR/pdf/2012/July/Anaeto%20et%20al.pdf'],
                    [u'http://www.fda.gov/downloads/Food/GuidanceComplianceRegulatoryInformation/GuidanceDocuments/ProduceandPlanProducts/UCM169112.pdf'],
                    [u'http://assets.wusc.ca/WUSCwebsite/Agribusiness-Information-Management-Advisor.pdf'],
                    [u'http://www.unesco.org/most/bpindi.htm'],
                    [u'http://www.worldcocoafoundation.org/wp-content/uploads/CocoaAction-Progress-Report-March-2015-English.pdf'],
                    [u'https://www.barry-callebaut.com/news/2016/04/barry-callebaut-cocoa-horizons-foundation-and-kim%E2%80%99s-chocolates-team-support-cocoa'],
                    [u'http://www.ispe.org/gmp-resources/what-is-gmp'],
                    [u'http://hdoa.hawaii.gov/qad/files/2012/12/GAP-task-force-report.pdf'],
                    [u'http://carolinafarmstewards.org/wp-content/uploads/2013/07/CFSA_GAPS-web.pdf'],
                    [u'http://farmingafrica.net/2015/05/farming-africa-welcomes-ghanaian-agricultural-journalists/?lang=en'],
                    [u'http://www.farmer-to-farmer.org/sites/default/files/resource/files/ltt_on_sps_issues_in_ghana_0.pdf'],
                    [u'http://gain.fas.usda.gov/Recent%20GAIN%20Publications/France%20Chooses%20Agro-Ecology%20for%20a%20More%20Sustainable%20Agriculture%20_Paris_France_1-14-2013.pdf'],
                    [u'http://thescipub.com/pdf/10.3844/ajassp.2012.673.677'],
                    [u'http://www.fda.gov/Food/GuidanceRegulation/FSMA/ucm304045.htm'],
                    [u'http://www.agnet.org/library.php?func=view_list&class=volume&type=11'],
                    [u'http://www.efreshglobal.com/eFresh/Content/Free.aspx?u=kgh'],
                    [u'https://ccafs.cgiar.org/blog/harnessing-valuable-indigenous-farm-knowledge-right-way'],
                    [u'http://www.cocoaconnect.org/training-material/good-agricultural-practices-sustainable-cocoa-production-guide-farmer-training-0'],
                    [u'http://www.agr.gc.ca/eng/science-and-innovation/agricultural-practices/soil-and-land/soil-and-water/soil-texture-and-water-quality/?id=1197483793077'],
                    [u'https://vtechworks.lib.vt.edu/handle/10919/51536'],
                    [u'http://pubs.sciepub.com/ajrd/2/2/3/'],
                    [u'http://www.pmi.com/eng/sustainability/good_agricultural_practices/documents/phil3758_alp%20brochure_v13.pdf'],
                    [u'http://etd.fcla.edu/UF/UFE0021342/ribeiro_c.pdf'],
                    [u'http://sibresearch.org/uploads/2/7/9/9/2799227/riber_h14-040_24-27.pdf'],
                    [u'http://adfsc.ae/en/pages/globalgab.aspx'],
                    [u'https://sustainabledevelopment.un.org/topics/topics/foodagriculture/decisions'],
                    [u'https://www.researchgate.net/publication/277253724_Effect_of_market_channel_farm_scale_and_years_in_production_on_mid-Atlantic_vegetable_producers%27_knowledge_and_implementation_of_Good_Agricultural_Practices'],
                    [u'http://gfvga.org/GAGAP/ga-gap-program/'],
                    [u'http://ieham.org/html/docs/Good_Agricultural_Practices_FAO.pdf'],
                    [u'http://www.bsnn.org/pdf/GoodAgriculturalPractice-DRPII-21728.pdf'],
                    [u'http://www.ethicalteapartnership.org/good-tea-starts-in-the-field/'],
                    [u'http://www.academia.edu/1243525/Indigenous_knowledge_agricultural_practices_and_food_security'],
                    [u'http://www.hse.gov.uk/risk/theory/alarp2.htm'],
                    [u'http://www.acfs.go.th/standard/download/eng/GAP_sweet_corn.pdf'],
                    [u'http://faculty.washington.edu/hgwolff/Evans%20UW_Request%2065_Enviro%20Impacts%20of%20Ag%20Technologies_03-17-2010.pdf'],
                    [u'http://istl.org/04-summer/article5.html'],
                    [u'http://sustainabledevelopment.un.org/index.php?menu=1269'],
                    [u'http://www.g-fras.org/en/knowledge/global-good-practice-notes.html?download=343:gg-note-10-rural-resource-centres-a-community-approach-to-agricultural-extension'],
                    [u'http://www.ciesin.org/docs/004-173/004-173.html'],
                    [u'http://www.iaea.org/icgfi/'],
                    [u'http://www.skillsdevelopment.org/pdf/Skills%20for%20Agriculture.pdf'],
                    [u'https://www.ams.usda.gov/services/grants/scbgp/specialty-crop'],
                    [u'https://www.ams.usda.gov/services/auditing/gap-ghp'],
                    [u'http://gaps.msue.msu.edu/USDA_GAP_2011.pdf'],
                    [u'http://www.syngentafoundation.org/index.cfm?pageID=594'],
                    [u'http://croplife.org/trainingthroughlocalpartnerships/honduras/'],
                    [u'http://www.iphandbook.org/handbook/chPDFs/ch16/ipHandbook-Ch%2016%2007%20Ammann%20Traditional%20Knowledge%20and%20Agriculture.pdf'],
                    [u'https://www.weadapt.org/knowledge-base/synergies-between-adaptation-and-mitigation/climate-smart-agriculture-put-into-practice-in-smallholder-dairy-development-project-in-kenya'],
                    [u'http://unfccc.int/files/documentation/submissions_from_observers/application/pdf/590.pdf'],
                    [u'http://www.agricultureauthority.go.ke/wp-content/uploads/2016/04/AFFA-form-1-D-editable-1.docx'],
                    [u'http://extension.uidaho.edu/kimberly/2013/04/good-agricultural-practices-gap-manual/'],
                    [u'http://www.europarl.europa.eu/webnp/webdav/users/jribot/public/JCM%20Agriculture/IAASTD%20Report.pdf'],
                    [u'http://nceats.omeka.chass.ncsu.edu/exhibits/show/raceandgender/menandwomen/jane_mckimmon'],
                    [u'http://tuspubs.tuskegee.edu/cgi/viewcontent.cgi?article=1066&context=pawj'],
                    [u'http://ngfn.org/resources/ngfn-database/knowledge/Fact%20Sheet%20GroupGAP.pdf'],
                    [u'http://www.ocl-journal.org/articles/ocl/pdf/2005/02/ocl2005122p134.pdf'],
                    [u'http://ign.ku.dk/english/employees/forest-nature-biomass/?pure=files%2F35157251%2FDE13_net_revision_2011_final.pdf'],
                    [u'http://www.fshn.hs.iastate.edu/angela-shaw-food-safety/good-agricultural-practices-workshop/'],
                    [u'http://www.qcin.org/documents/GAP/INDGAP-BASIC-REQUIREMENTS.pdf'],
                    [u'http://www.proakis.eu/sites/www.proakis.eu/files/Topic%202-%20Poland.pdf'],
                    [u'http://www.iita.org/projects-asset?p_p_id=101_INSTANCE_9Kn9&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_pos=2&p_p_col_count=4&_101_INSTANCE_9Kn9_struts_action=%2Fasset_publisher%2Fview_content&_101_INSTANCE_9Kn9_urlTitle=fast-tracking-the-access-to-improved-and-popular-varieties-of-root-crops-by-smallholder-farmers&_101_INSTANCE_9Kn9_type=content&redirect=%2Fprojects'],
                    [u'https://www.feedingknowledge.net/home/-/bsdp/10676/en_GB'],
                    [u'https://www.routledge.com/art/series/ECIAB'],
                    [u'http://www1.agric.gov.ab.ca/$Department/deptdocs.nsf/all/agdex13331'],
                    [u'http://www.idrc.ca/EN/AboutUs/Donor_Partnerships/Canadian_International_Food_Security_Research_Fund/Pages/108125.aspx'],
                    [u'http://www.monitor.co.ug/Magazines/Farming/Better-farming-methods-cooperatives-boost-productivity/-/689860/3030832/-/vw17j9z/-/index.html'],
                    [u'http://www.oecd.org/greengrowth/sustainable-agriculture/2739771.pdf'],
                    [u'http://extension.psu.edu/youth/betterkidcare/early-care/our-resources/tip-pages/tips/exploring-developmentally-appropriate-practice'],
                    [u'http://www.tarim.gov.tr/Konular/Good-Agricultural-Practices'],
                    [u'http://www.ciesin.org/TG/AG/iksys.html'],
                    [u'http://www.ecologyandsociety.org/vol14/iss1/art48/'],
                    [u'https://www.epa.gov/agriculture/agriculture-crops'],
                    [u'http://www.joe.org/joe/2015october/rb3.php'],
                    [u'http://www.ifla.org/past-wlic/2011/78-abioye-en.pdf'],
                    [u'https://www.wageningenur.nl/en/show/Increase-of-knowledge-leads-to-implementation-of-good-agricultural-practices-in-Kenya.htm'],
                    [u'http://ourworld.unu.edu/en/japanese-agricultural-heritage-systems-recognized'],
                    [u'http://eric.ed.gov/?id=EJ1082954'],
                    [u'http://thescipub.com/pdf/10.3844/ajassp.2010.1379.1386'],
                    [u'http://hwww.searca.org/news-and-events/searca-in-the-news/1764-good-agricultural-practices-traditional-rice-wisdom-can-alone-increase-rice-production-study'],
                    ]
            return lista
            
 #FALLAS:   
 #fails=['http://www.ncbi.nlm.nih.gov/pubmed/6996921'],['http://www.pureceylontea.com/index.php/features/fine-ceylon-tea/manufacturing']
 #PDFs 
 #urls=['http://www.sspindia.com/pdf/instant-coffe-catalogue.pdf']

#searchKeys:
#technology to produce tea
#tea transgenic technology
#pruning techniques tea leaves
 
